services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony-api
    restart: unless-stopped
    #ports:
      #- "8000:9000"
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: "mysql://dev:dev123@mysql:3306/symapi?serverVersion=8.0.44&charset=utf8mb4"
    depends_on:
      - mysql
    networks:
      - symfony-network
  nginx:
    image: nginx:alpine
    container_name: nginx-symfony
    ports:
      - "8000:80"  # HTTP
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - symfony
    networks:
      - symfony-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symapi
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - symfony-network
    #ports:
      #- "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: dev
      PMA_PASSWORD: dev123
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - symfony-network

volumes:
  mysql_data:

networks:
  symfony-network:
    driver: bridge
